require("rpLi.plugins-setup")
require("rpLi.core.options")
require("rpLi.core.keymaps")
require("rpLi.core.colorscheme")
require("rpLi.plugins.comment")
-- require("rpLi.plugins.nvim-tree")
require("rpLi.plugins.neo-tree")
require("rpLi.plugins.lualine")
require("rpLi.plugins.telescope")
require("rpLi.plugins.nvim-cmp")
require("rpLi.plugins.lsp.mason")
require("rpLi.plugins.lsp.lspsaga")
require("rpLi.plugins.lsp.lspconfig")
-- require("rpLi.plugins.lsp.null-ls")
require("rpLi.plugins.autopairs")
require("rpLi.plugins.treesitter")
require("rpLi.plugins.gitsigns")
require("rpLi.plugins.distant")
require("rpLi.plugins.texmagic")
require("rpLi.plugins.bufferline")
require("rpLi.plugins.ident-blankline")
require("rpLi.plugins.neotest")
require("rpLi.plugins.statuscol")
